# Generated by Django 5.1.7 on 2025-03-23 16:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_profile_user_userspeech'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userspeech',
            old_name='durattion',
            new_name='duration',
        ),
    ]
