# Generated by Django 5.1.7 on 2025-03-27 10:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_rename_durattion_userspeech_duration'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpeechMetrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clarity', models.FloatField(blank=True, null=True)),
                ('tone', models.FloatField(blank=True, null=True)),
                ('volume', models.FloatField(blank=True, null=True)),
                ('pauses', models.FloatField(blank=True, null=True)),
                ('pacing', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('speech', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='metrices', to='api.userspeech')),
            ],
        ),
    ]
